credentials:
  usernames:
    demo_lawyer:
      email: demo@lawfirm.pr
      name: Demo Lawyer
      password: $2b$12$... # Use stauth.Hasher to hash passwords
      firm_id: 1

cookie:
  name: professional_hubs_auth
  key: your-secret-key-here-change-this
  expiry_days: 30